#' Set up and use virtual environments
#'
#' Set up and use Python virtual environments for isolated execution of Python code with appropriate versions of all Python packages.
#' 
#' @param envname String containing the name of the virtual environment to create (for \code{setupVirtualEnv}) or use (other functions).
#' @param packages Character vector containing the names of Python packages to install into the virtual environment.
#' It is required to include version numbers in each string.
#' @param pkgpath String specifying the path to the R package installation directory, usually used in an R package installation script.
#' If \code{NULL}, it defaults to \code{\link{virtualenv_root}}.
#' @param pkgname String specifying the package name, if the function is used inside an R package.
#' @param overwrite Logical scalar indicating whether an existing virtual environment should be overwritten.
#' If \code{FALSE} and the virtual environment is already present, \code{setupVirtualEnv} is a no-op.
#' 
#' @return 
#' \code{setupVirtualEnv} will create a virtual environment - at the designated location if \code{pkgpath} is specified, or at the default location for virtual environments otherwise.
#' It returns a character vector containing \code{packages}.
#'
#' \code{useVirtualEnv} will load the specified virtual environment into the R session.
#' It returns a string specifying the path to the virtual environment.
#' If \code{dry=TRUE}, the character vector is returned without loading the virtual environment.
#'
#' @details
#' Use of virtual environments is the recommended approach for Bioconductor packages to interact with the \pkg{basilisk} Python instance.
#' This avoids version conflicts within an R session when different Bioconductor packages (or even different functions within a single package) require incompatible versions of Python packages.
#'
#' Developers of Bioconductor packages should call \code{setupVirtualEnv} with an appropriate \code{pkgpath} (usually generated by \code{system.file(package=PKGNAME)}) in an \code{.onLoad} function.
#' This will install the relevant Python packages during R package installation (and be skipped 
#' The \pkg{son.of.basilisk} example in the \code{inst} directory of \pkg{basilisk} can be used as an example.
#'
#' @section Dealing with versioning: 
#' Pinned version numbers must be present for all requested packages in \code{packages}.
#' This improved predictability makes debugging much easier when the R package is installed and executed on different systems.
#' Explicit versions are also mandatory for all dependencies of requested packages,
#' which is again necessary to ensure that the same versions are deployed across systems.
#'
#' The only exception to the above rule is for \dQuote{core} packages that are installed into the \pkg{basilisk} Python instance.
#' If your requested packages depend on these core packages, \code{setupVirtualEnv} will automatically install them without requiring them to be listed with explicit version numbers in \code{packages}.
#' You can also request a core package without specifying the version, which will automatically be pinned for you.
#' A full list of core packages with pinned versions is provided at \code{\link{listCorePackages}}.
#'
#' The exception to the exception occurs when your requested packages are not compatible with the pinned versions of the core packages.
#' In such cases, the compatible versions of the core packages must again be explicitly listed in \code{packages}.
#'
#' @section Wrangling the PYTHONPATH:
#' A side-effect of \code{useVirtualEnv} with \code{dry=FALSE} is that the \code{"PYTHONPATH"} environment variable is unset for the duration of the R session
#' (or \pkg{basilisk} process, depending on the back-end chosen by \code{\link{basiliskStart}}).
#' This is a deliberate choice to avoid compromising the version guarantees if \code{\link{import}} is allowed to search other locations beyond the virtual environment.
#'
#' @author Aaron Lun
#' 
#' @examples
#' setupVirtualEnv('my_package_A', c('pandas==0.25.3',
#'     "python-dateutil==2.8.1", "pytz==2019.3"))
#' useVirtualEnv("my_package_A")
#' X <- reticulate::import("pandas")
#' X$`__version__`
#'
#' # No need to list versions of core packages, 
#' # or to list them at all if they are dependencies.
#' setupVirtualEnv('my_package_A_alt', 'pandas')
#' 
#' @seealso
#' \code{\link{basiliskStart}}, for how these virtual environments should be used.
#'
#' \code{\link{listCorePackages}}, for a list of core Python packages with pinned versions.
#' @export
#' @importFrom reticulate virtualenv_create virtualenv_install virtualenv_remove
#' virtualenv_root
setupVirtualEnv <- function(envname, packages, pkgpath=NULL, overwrite=is.null(pkgpath)) {
    if (!overwrite && file.exists(file.path(pkgpath, "basilisk", envname))) {
        return(NULL)
    }

    core.data <- listCorePackages()
    core.full <- core.data$full
    core.names <- core.data$name

    versioned <- grepl("==", packages)
    if (!all(versioned)) {
        unversioned <- packages[!versioned]
        core.match <- match(unversioned, core.names)
        if (!any(is.na(core.match))) {
            # Core packages only need their name specified, 
            # and we will automatically use the core version.
            packages[!versioned] <- core.full[core.match]
        } else {
            stop(sprintf("version must be explicitly specified for '%s'", unversioned[is.na(core.match)][1]))
        }
    }

    pkg.names <- .full2pkg(packages)
    if (dup <- anyDuplicated(pkg.names)) {
        stop(sprintf("redundant listing of '%s'", pkg.names[dup]))
    }

    #############################
    # Unsetting this variable, otherwise it seems to override the python=
    # argument in virtualenv_create() (see LTLA/basilisk#1).
    old.retpy <- Sys.getenv("RETICULATE_PYTHON")
    if (old.retpy!="") {
        Sys.unsetenv("RETICULATE_PYTHON")
        on.exit(Sys.setenv(RETICULATE_PYTHON=old.retpy), add=TRUE)
    }

    old.pypath <- Sys.getenv("PYTHONPATH")
    if (old.pypath!="") {
        Sys.unsetenv("PYTHONPATH")
        on.exit(Sys.setenv(PYTHONPATH=old.pypath), add=TRUE)
    }

    # Use environment variable for testing purposes only;
    # this should not be exposed to the clients.
    py.cmd <- Sys.getenv("BASILISK_TEST_PYTHON", useBasilisk())

    #############################
    # Creating a virtual environment in an appropriate location.
    if (!is.null(pkgpath)) {
        vdir <- file.path(pkgpath, "basilisk")
        dir.create(vdir, recursive=TRUE, showWarnings=FALSE)
        old.work <- Sys.getenv("WORKON_HOME")
        Sys.setenv(WORKON_HOME=vdir)
        on.exit(Sys.setenv(WORKON_HOME=old.work), add=TRUE)
    }

    target <- file.path(path.expand(virtualenv_root()), envname)
    if (file.exists(target)) {
        unlink(target, recursive=TRUE)
    }
    virtualenv_create(envname, python=py.cmd)
    env.cmd <- file.path(target, "bin", "python3")

    #############################
    # ROUND 1: Seeing what the incoming packages need.
    previous <- .basilisk_freeze(env.cmd)
    virtualenv_install(envname, packages, ignore_installed=FALSE)
    updated <- .basilisk_freeze(env.cmd)

    # If all newly added packages are accounted for, we finish up.
    # We deliberately exclude any core packages in 'packages' so that they show
    # up in 'added' and thus are candidates for reinstallation into the base basilisk instance.
    added <- setdiff(updated, c(previous, packages[!packages %in% core.full]))
    if (length(added)==0L) {
        return(NULL)
    }

    virtualenv_remove(envname, confirm=FALSE) # Removing Round 1 to start from a fresh installation.

    #############################
    # Figuring out if any of the newly downloaded packages are core packages.
    # If so, we install them to the base installation if we have access;
    # otherwise, we add it to our virtual environment.
    added.names <- .full2pkg(added)
    if (any(unlisted.noncore <- !added.names %in% core.names)) {
        stop(sprintf("need to list dependency on '%s'", added[unlisted.noncore][1]))
    }
    overlaps <- core.names %in% added.names 

    if (file.access(system.file(package="basilisk"), 2)==0L) {
        .basilisk_install(core.full[overlaps], py.cmd=py.cmd)
        virtualenv_create(envname, python=py.cmd) 
    } else {
        virtualenv_create(envname, python=py.cmd) 
        virtualenv_install(envname, core.full[overlaps], ignore_installed=FALSE)
    }

    #############################
    # ROUND 2: Trying again after lazy installation of the core packages.
    previous <- .basilisk_freeze(env.cmd)
    virtualenv_install(envname, packages, ignore_installed=FALSE)
    updated <- .basilisk_freeze(env.cmd)

    if (any(!updated %in% c(previous, packages))) {
        added <- setdiff(updated, c(previous, packages))
        stop(sprintf("need to list dependency on '%s'", added[1]))
    }

    NULL
}

.basilisk_install <- function(packages, py.cmd=useBasilisk()) {
    system2(py.cmd, c("-m", "pip", "install", packages))
}

.basilisk_freeze <- function(py.cmd) {
    system2(py.cmd, c("-m", "pip", "freeze"), stdout=TRUE)
}

#' @export
#' @rdname setupVirtualEnv
#' @param dry Logical scalar indicating whether only the directory should be returned without loading the virtual environment.
#' @param required Logical scalar indicating whether an error should be raised if the requested virtual environment cannot be found.
#' @importFrom reticulate use_virtualenv virtualenv_root
useVirtualEnv <- function(envname, pkgname=NULL, dry=FALSE, required=TRUE) {
    old.retpy <- Sys.getenv("RETICULATE_PYTHON")
    Sys.unsetenv("RETICULATE_PYTHON")
    if (old.retpy!="") {
        on.exit(Sys.setenv(RETICULATE_PYTHON=old.retpy))
    }

    if (!is.null(pkgname)) {
        vdir <- system.file("basilisk", package=pkgname, mustWork=TRUE)
    } else {
        vdir <- normalizePath(virtualenv_root())
    }
    vdir <- file.path(vdir, envname)

    if (!dry) {
        # Don't even try to be nice and add an on.exit() clause to protect the
        # global session. This is deliberate; if we're using a virtual
        # environment, and someone tries to import package in the global session,
        # and Python looks somewhere else other than our virtual environment via
        # the PYTHONPATH, we can get the wrong package loaded. 
        Sys.unsetenv("PYTHONPATH")
        use_virtualenv(vdir, required=required)
    }
    vdir
}
